eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
            #defaultZone: http://10.181.12.8:8761/eureka

server:
    port: 8088
    tomcat:
        accept-count: 100000
        max-connnetions: 100000
        max-threads: 5000

feign:
    hystrix:
        enabled: true

hystrix:
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 10000

ribbon:
    ConnectTimeout: 1000
    ReadTimeout: 1000
    MaxAutoRetriesNextServer: 1
    MaxAutoRetries: 1

serviceA:
    ribbon:
      ReadTimeout: 500
      MaxAutoRetriesNextServer: 0
      MaxAutoRetries: 0
      OkToRetryOnAllOperations: true

security:
  basic:
    enabled: false # 关闭基于HTTP basic的认证

logging:
    level:
      org.springframework.web.servlet.DispatcherServlet: info

spring:
  redis:
    #cluster:
    #  nodes: 10.181.12.32:9179,10.181.12.33:9179,10.181.12.34:9179,10.181.12.35:9179,10.181.12.36:9179,10.181.12.37:9179,10.181.12.38:9179,10.181.12.39:9179,10.181.12.40:9179,10.181.12.43:9179,10.181.12.44:9179,10.181.12.46:9179,10.181.12.48:9179,10.181.12.51:9179,10.181.12.52:9179,10.181.12.53:9179,10.181.12.66:9179,10.181.12.68:9179,10.181.12.69:9179,10.181.12.70:9179
    pool:
      max-active: 500 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 100 # 连接池中的最大空闲连接
      min-idle: 20  # 连接池中的最小空闲连接
    database: 0  # Redis数据库索引(默认为0)
    timeout: 60000  # 连接超时时间（毫秒）
    #password: redis123
    host: 127.0.0.1
    port: 6379



cache:
  customized:
    defualtExpiration: 120 #缓存默认失效时间 单位:秒
    chapterinfo:
      #expiration: 30



