server:
  port: 8762
  #euru prot
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 1  #服务失效时间
    lease-renewal-interval-in-seconds: 1     #服务续约时间间隔
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/